git:
  filters:
  - filter_type: file
    source_file: core/src/main/resources/i18n/spark_i18n.properties
    file_format: UNICODEPROPERTIES
    translation_files_expression: 'core/src/main/resources/i18n/spark_i18n_<lang>.properties'
    source_language: en
